SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE IF NOT EXISTS `module_scorm_scormvars` (
  `id_utente` int(10) UNSIGNED NOT NULL,
  `scoobject` varchar(255) CHARACTER SET utf8 NOT NULL,
  `scoid` varchar(255) CHARACTER SET utf8 NOT NULL,
  `varname` varchar(255) CHARACTER SET utf8 NOT NULL,
  `varvalue` text CHARACTER SET utf8,
  `timestamp` bigint(10) NOT NULL,
  PRIMARY KEY (`id_utente`,`scoobject`(100),`scoid`(100),`varname`(100),`timestamp`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
