var datatable;

function initDoc()
{
	initDataTables();

}

function initDataTables() {

	datatable = $j('#newsletterHistoryDetails').dataTable( {
                "bFilter": true,
                "bInfo": false,
                "bSort": true,
                "bAutoWidth": true,
                "bPaginate" : false,
                'aoColumns': [
                              // first empty column generated by ADA HTML engine, let's hide it
                                { "bSearchable": false,
                                  "bVisible":    false },
                                { "sWidth" : "70%"} ,
                                { "sType": "date-eu" , "sWidth" : "22%"},                                           
                                { "sWidth" : "8%"} 
//                                null,
//                                { "bSearchable" : false, "bSortable" : false, "sWidth" : "15%"}
                            ],
                "oLanguage": {
                    "sUrl": HTTP_ROOT_DIR + "/js/include/jquery/dataTables/dataTablesLang.php"
                 }
	}).show();
}
